// GENERATED by tools/pin-dictionary.mjs, run `npm run pin-dict` to refresh.

import type { DictionaryRelease } from "./dictionarySource.ts";

const PIN: DictionaryRelease = {
  version: "20260723",
  url: "https://files.pythonhosted.org/packages/46/fe/68a146fced55319af40d25a4fe19b94c3a988406ce4674a8b2f0237fbc9f/sudachidict_core-20260723-py3-none-any.whl",
  sha256: "b3869ce6b12b4bfa09575dc19030703bb669ab41bac12a74cafcbb28c6be2498",
  size: 72275897
};

/**
 * What shipped with this build. Used as the offline fallback when no metadata
 * source answers, and as the baseline a user can always install.
 */
export function pinnedRelease(): DictionaryRelease {
  return PIN;
}
