// GENERATED by tools/pin-dictionary.mjs, run `npm run pin-dict` to refresh.
//
// The dictionary release each build expects, so building needs no network and a
// version change appears in a diff instead of happening silently.
//
// Every digest here is one the publisher asserted, taken from the GitHub release
// that carries the artifact. That is what lets a download come from a mirror, or
// from a third-party relay, and still be trusted: the bytes are checked against
// this, never against whoever served them.
//
// Pinned 2026-08-07.

import type { DictionaryEdition, DictionaryRelease } from "./dictionarySource.ts";

const PINS: Record<DictionaryEdition, Omit<DictionaryRelease, "edition">> = {
  small: {
    version: "20260723",
    url: "https://github.com/WorksApplications/SudachiDict/releases/download/v20260723/sudachidict_small-20260723-py3-none-any.whl",
    sha256: "c10c7541795c4cf501ddd15f456409d0b75b84339c5961dd045fa922378b687a",
    size: 41770618
  },
  core: {
    version: "20260723",
    url: "https://github.com/WorksApplications/SudachiDict/releases/download/v20260723/sudachidict_core-20260723-py3-none-any.whl",
    sha256: "b3869ce6b12b4bfa09575dc19030703bb669ab41bac12a74cafcbb28c6be2498",
    size: 72275897
  },
  full: {
    version: "20260723",
    url: "https://github.com/WorksApplications/SudachiDict/releases/download/v20260723/sudachidict_full-20260723-py3-none-any.whl",
    sha256: "c0abc12bb4aaab8042a8fb8cf4d6ce0dd78b97f099cecf932665e22688ab5ed9",
    size: 126614513
  }
};

/**
 * What shipped with this build. Used as the offline fallback when no metadata
 * source answers, and as the baseline a user can always install.
 *
 * Carries its URL. Without one the offline fallback knew the exact version,
 * size and hash it wanted and had nowhere to fetch it from, so every metadata
 * source failing meant no install was possible at all.
 */
export function pinnedRelease(edition: DictionaryEdition): DictionaryRelease {
  return { edition, ...PINS[edition] };
}
